### ISSUE TITLE
ISSUE vs. retire

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv-verification/RVVI#9]
https://github.com/riscv-verification/RVVI/tree/main/RVVI-VLG states:

> ISSUE
> 
> This is the maximum number of instructions that can be retired during a valid event.

Can the signal be renamed to RETIRE if that is what is means?

**Comment by Silabs-ArjanB** [comment]
This might cause some confusion on the RTL side. For example the existing CV32E40P can only issue one instruction per cycle but it can retire two instructions per cycle (due to its pipeline architecture).

**Comment by eroom1966** [comment]
OK, interesting point- so your suggestion is to dimension this on the maximum number of instructions that can retire concurrently. We had not fully considered the fact that two instructions could retire simultaneously, even though only one could be issued. 
You could still define the parameter to be value 2, which would allow you to show 2 instructions retiring simultaneously, but you have a valid point that the name does not quite match the meaning
Thanks for raising this

**Comment by bit-hack** [comment]
I have renamed the signal to `RETIRE` as suggested and updated the documentation to reflect this.  I'll close this ticket, but please re-open if you think there is still more work to do regarding this.
